# Generated by Django 4.2.9 on 2024-02-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherly_app', '0039_remove_emailsettings_email_host_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_commande',
            name='add_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bon_commande',
            name='add_g',
            field=models.IntegerField(default=0),
        ),
    ]
