# Generated by Django 5.0.1 on 2024-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0060_table_bl_t2add"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="produit_images/"),
        ),
    ]
