# Generated by Django 5.0.1 on 2024-03-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0061_produit_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="image",
        ),
    ]
