# Generated by Django 5.0.1 on 2024-03-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0062_remove_produit_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("conditionnement_count", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="produit_images/"
                    ),
                ),
                (
                    "famille",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sherly_app.famille",
                    ),
                ),
            ],
        ),
    ]
