# Generated by Django 5.0.1 on 2024-03-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0064_image_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banniere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bannier_images/")),
            ],
        ),
    ]
