# Generated by Django 5.0.1 on 2024-03-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sherly_app", "0065_banniere"),
    ]

    operations = [
        migrations.AddField(
            model_name="societe",
            name="remise",
            field=models.IntegerField(default=0),
        ),
    ]
